name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MY_APP_USERNAME: ${{ secrets.MY_APP_USERNAME }}
      MY_APP_PASSWORD: ${{ secrets.MY_APP_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Add more steps for your build process...
